### ISSUE TITLE
look over utils for attribution

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/utils#1]
note to self, make sure none of the attribution banners were stripped when the "modularize" plugin was run. If I recall, there were a couple of methods from mout, like `forEach` and `isArguments`

**Comment by tunnckoCore** [comment]
this `isArguments` is strange. How you pass second argument to `kind-of` when it dont support second argument? lol

``` js
module.exports = typeOf(arguments, 'arguments')
```

and this check will pass so will return this func.. hm.

``` js
function isArguments(val) {
  return typeOf(val, 'arguments');
}
```

**Comment by jonschlinkert** [comment]
here is the [code coverage](https://github.com/jonschlinkert/utils#code-coverage). I'm still working to get everything on that list covered.

**Comment by tunnckoCore** [comment]
yep I see, I made some docs and more test, but cant generate readme and PR, because the verb ^^
im going to trick the bugs, haha

**Comment by jonschlinkert** [comment]
yeah I was having issues with the `apitoc` helper earlier too. you can see that in the current readme here: https://github.com/jonschlinkert/utils#code-links. It didn't output anything. 

Part of the problem is that I'm trying to refactor verb, and to do it right I need to using the new verb as much as possible to keep testing it in real usage. But then I have to switch back to the current verb. it just is bound to create inconsistencies for a little bit while it's in transition. sorry for the issues

**Comment by tunnckoCore** [comment]
Yea, okey. But how to make PR in this case, I'm curios?

**Comment by jonschlinkert** [comment]
oh, sorry just remove that helper. it's not necessary. I don't ever want to hold up actual progress with code just because of a readme issue. in the future, if you want to add docs for code in a pr and verb has a problem, just add the docs to the pr comment or something. I usually don't give people a hard time about that stuff, I mainly care about the code quality.

**Comment by jonschlinkert** [comment]
thanks for asking, I appreciate it

**Comment by jonschlinkert** [comment]
and btw, verb is pretty much the [most amazing project I've created](https://github.com/verbose/verb-helper-codelinks#why-use-verb). There is no denying that.  :)
