### ISSUE TITLE
doh... again bugs

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/utils#2]
Again verb-related bugs. When run `verb readme` it fails, in short.. fails `apitoc`

```
domainThrown: false,
  name: 'ReferenceError',
  message: 'apitoc is not defined',
  stack: 'ReferenceError: apitoc is not defined\n    at eval (lodash.templateSources[0]:25:59)\n    at Object.engine.render (/home/charlike/dev/utils/node_modules/verb/node_modules/template/node_modules/engine-cache/index.js:172:43)\n    at Template.renderAsync (/home/charlike/dev/utils/node_modules/verb/node_modules/template/index.js:1951:12)\n    at Template.renderBase (/home/charlike/dev/utils/node_modules/verb/node_modules/template/index.js:1821:15)\n    at Template.renderTemplate (/home/charlike/dev/utils/node_modules/verb/node_modules/template/index.js:1901:15)\n    at Template.render (/home/charlike/dev/utils/node_modules/verb/node_modules/template/index.js:1990:17)\n    at DestroyableTransform._transform (/home/charlike/dev/utils/node_modules/verb/lib/plugins/render.js:54:12)\n    at DestroyableTransform.Transform._read (/home/charlike/dev/utils/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at DestroyableTransform.Transform._write (/home/charlike/dev/utils/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)\n    at doWrite (/home/charlike/dev/utils/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)',
  showStack: true,

```

**Comment by jonschlinkert** [comment]
https://github.com/verbose/verb-cli/issues/3

**Comment by jonschlinkert** [comment]
> Again verb-related bugs.

you're killing me lol. be nice, and create verb related issues on verb, thanks!

**Comment by tunnckoCore** [comment]
> ou're killing me lol.

haha I just dont want to use or look verb, but you force us. ;d

> create verb related issues on verb

Okey, I'll try next time.

**Comment by jonschlinkert** [comment]
I'm just messing with you!

> but you force us. ;d

Are you sure about that? I don't remember ever telling anyone to run verb. This project is the first time I put that in the readme. I usually have a personal policy of not asking other developers to do things that I can do for them easier than they can do for me. e.g. I know verb, why make them do it? but hey, thank you for being great about it and trying!

**Comment by tunnckoCore** [comment]
> Are you sure about that? I don't remember ever telling anyone to run verb.

Yea, you dont telling, but to do PR they should run verb. Okey, maybe only in this case/lib.
