### ISSUE TITLE
No verb footer?

### ISSUE THREAD

**Issue by tomByrer** [jonschlinkert/utils#4]
I've been so accustomed to seeing on all your projects
`This file was generated by verb-cli on Monty DD, YYYY.`
I'm kinda weirded out that this repo's README is missing it.  You even require us to use verb to rebuild docs.  Something broke?

**Comment by jonschlinkert** [comment]
lol, you don't miss a step! I'm about to push up a pretty awesome refactor of verb, and I've been trying to use that as much as possible locally to get these kinds kinks worked out. so technically, nothings broken - it's being broken-in!

> You even require us to use verb to rebuild docs.

I knew I'd get a hard time for that lol. 

thanks for letting me know!

**Comment by tomByrer** [comment]
[I see](https://github.com/assemble/verb/tree/refactor/docs)
cheers

**Comment by jonschlinkert** [comment]
here is a preview of one of the things that will make this next release awesome. 

## Diffs

This is a visual diff of the pre-render and post-render content of a template that has an error (the error is `[object Object]` where the author name should be):

![screen shot 2015-03-26 at 11 54 00 pm](https://cloud.githubusercontent.com/assets/383994/6861841/8c0d09d0-d413-11e4-955b-4a42aa0ff33d.png)

**Comment by tomByrer** [comment]
Never thought of diff-ing a template to show how it renders!
